# Knapsack with Canadian Currency

m = []
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])
m.append([])

def ks(v, w, n, W):
	for j in range(W):
		m[0].append(0)

	for i in range(1, n):
		for j in range(W):
			if w[i] <= j:
				m[i][j] = max(m[i-1][j], m[i-1][j-w[i]] + v[i])
			else:
				m[i][j] = m[i-1][j]
	print(m)

v = [1, 5, 10, 25]
w = [1, 1, 1, 1]
n = 10
W = 67
ks(v, w, n, W)