language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
script:
  - npm test
deploy:
  provider: s3
  access_key_id: $NOTES_AWS_ACCESS_KEY
  secret_access_key: $NOTES_AWS_SECRET_KEY
  bucket: "brmc-notes-app"
on:
  branch: master